pluginGroup = net.dyadix.typengo
pluginName = TypeNGo
pluginVersion = 1.0.3

# See https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
pluginSinceBuild = 261.1

# IntelliJ Platform target (IntelliJ IDEA Ultimate 2026.1)
# Note: starting with 2025.3, only IntelliJ IDEA Ultimate (IU) is published as a target IntelliJ Platform.
platformType = IU
platformVersion = 2026.1

# Java target compatibility
javaVersion = 21

org.gradle.jvmargs=-Xmx2g -XX:+UseParallelGC
org.gradle.caching=true
org.gradle.configuration-cache=false
kotlin.stdlib.default.dependency=false
